# Generated by Django 4.0.3 on 2022-04-06 03:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 3, 36, 17, 554319, tzinfo=utc)),
        ),
    ]
